/opt/devkitpro/portlibs/switch/bin/aarch64-none-elf-cmake . -DRUN_IN_PLACE=1 -DSWITCH=1 -DENABLE_SOUND=0 -DENABLE_CURSES=0 -DENABLE_GETTEXT=0 -DENABLE_GLES=0 -DENABLE_POSTGRESQL=0 -DENABLE_REDIS=0 -DENABLE_SPATIAL=0 -DUSE_LEVELDB=0 -DBUILD_SHARED_LIBS=0 -USE_DLOPEN=0 -DCMAKE_BUILD_TYPE=Release

make -j4

./package.sh